### ISSUE TITLE
Select List Focussing

### ISSUE THREAD

**Issue by selbjx** [vadikom/poshytip#16]
Hi,

Excellent plugin however Tried to assign this to a select list (dropdownlist) and presented an undesired behaviour whereby when using the mouse to navigate the dropdown, field focus appears to be lost, causing the list to close.

Using with jquery 1.8.3, same in IE8, IE9, fine in firefox 19

Jon

**Comment by vadikom** [comment]
This is fixed in v1.2.

**Comment by IgorErmakov** [comment]
Hi Vadikom,

The bug still exists for IE 11
https://jsfiddle.net/c4a9w69k/

layer disappears if I mouse over on a selectbox inside of the tooltip. It works nice in FF, Safari. but not in IE11. 

PS: Anyway, It's very good plugin! Use it for a large project. 

Thank You
